# Generated by Django 3.2.5 on 2021-07-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SupplierName', models.CharField(max_length=255)),
                ('OnlineShopURL', models.URLField()),
                ('Telephone', models.CharField(max_length=15)),
                ('EmailAddress', models.EmailField(max_length=254)),
            ],
        ),
    ]
