# Generated by Django 3.2.5 on 2021-07-23 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0004_customer_purchasedstockdetails_soldgooddetails_soldgoodinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductCategory', models.CharField(max_length=255, null=True)),
                ('Count', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IMS.productcategory'),
        ),
    ]
