# Generated by Django 3.2.5 on 2021-07-23 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0005_auto_20210723_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='Count',
        ),
    ]
